(cl:defpackage basics-srv
  (:use )
  (:export
   "WORDCOUNTT"
   "<WORDCOUNTT-REQUEST>"
   "WORDCOUNTT-REQUEST"
   "<WORDCOUNTT-RESPONSE>"
   "WORDCOUNTT-RESPONSE"
   "WORDCOUNTTEST"
   "<WORDCOUNTTEST-REQUEST>"
   "WORDCOUNTTEST-REQUEST"
   "<WORDCOUNTTEST-RESPONSE>"
   "WORDCOUNTTEST-RESPONSE"
  ))

