// Generated by gencpp from file basics/WordCountTest.msg
// DO NOT EDIT!


#ifndef BASICS_MESSAGE_WORDCOUNTTEST_H
#define BASICS_MESSAGE_WORDCOUNTTEST_H

#include <ros/service_traits.h>


#include <basics/WordCountTestRequest.h>
#include <basics/WordCountTestResponse.h>


namespace basics
{

struct WordCountTest
{

typedef WordCountTestRequest Request;
typedef WordCountTestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCountTest
} // namespace basics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::basics::WordCountTest > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::basics::WordCountTest&) { return value(); }
};

template<>
struct DataType< ::basics::WordCountTest > {
  static const char* value()
  {
    return "basics/WordCountTest";
  }

  static const char* value(const ::basics::WordCountTest&) { return value(); }
};


// service_traits::MD5Sum< ::basics::WordCountTestRequest> should match 
// service_traits::MD5Sum< ::basics::WordCountTest > 
template<>
struct MD5Sum< ::basics::WordCountTestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::basics::WordCountTest >::value();
  }
  static const char* value(const ::basics::WordCountTestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::basics::WordCountTestRequest> should match 
// service_traits::DataType< ::basics::WordCountTest > 
template<>
struct DataType< ::basics::WordCountTestRequest>
{
  static const char* value()
  {
    return DataType< ::basics::WordCountTest >::value();
  }
  static const char* value(const ::basics::WordCountTestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::basics::WordCountTestResponse> should match 
// service_traits::MD5Sum< ::basics::WordCountTest > 
template<>
struct MD5Sum< ::basics::WordCountTestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::basics::WordCountTest >::value();
  }
  static const char* value(const ::basics::WordCountTestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::basics::WordCountTestResponse> should match 
// service_traits::DataType< ::basics::WordCountTest > 
template<>
struct DataType< ::basics::WordCountTestResponse>
{
  static const char* value()
  {
    return DataType< ::basics::WordCountTest >::value();
  }
  static const char* value(const ::basics::WordCountTestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASICS_MESSAGE_WORDCOUNTTEST_H
